FROM centos:7
MAINTAINER NsLib "mdl2009@vip.qq.com"

ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN mkdir -p /go && \
        chmod -R 777 /go && \
        yum -y install git golang make && \
        yum clean all

ADD . /go/src/github.com/open-falcon/falcon-plus
WORKDIR /go/src/github.com/open-falcon/falcon-plus

RUN make install
RUN make all

WORKDIR /go
