FROM centos:7
MAINTAINER NsLib "mdl2009@vip.qq.com"

ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN mkdir -p /go && \
        chmod -R 777 /go && \
        yum -y install git golang && \
        yum clean all

WORKDIR /go
