CMD = agent aggregator graph hbs judge nodata transfer gateway api alarm
TARGET = open-falcon
PACKAGES ?= $(shell go list ./... | grep -v /vendor/)
GOFILES := $(shell find . -name "*.go" -type f -not -path "./vendor/*")
GOFMT ?= gofmt "-s"
VERSION := $(shell cat VERSION)

all: $(CMD) $(TARGET)

.PHONY: misspell-check
misspell-check:
	@hash misspell > /dev/null 2>&1; if [ $$? -ne 0 ]; then \
		go get -u github.com/client9/misspell/cmd/misspell; \
	fi
	misspell -error $(GOFILES)

.PHONY: misspell
misspell:
	@hash misspell > /dev/null 2>&1; if [ $$? -ne 0 ]; then \
		go get -u github.com/client9/misspell/cmd/misspell; \
	fi
	misspell -w $(GOFILES)

install:
	@hash govendor > /dev/null 2>&1; if [ $$? -ne 0 ]; then \
		go get -u github.com/kardianos/govendor; \
	fi
	govendor sync

vet:
	go vet $(PACKAGES)

fmt:
	$(GOFMT) -w $(GOFILES)

.PHONY: fmt-check
fmt-check:
	# get all go files and run go fmt on them
	@diff=$$($(GOFMT) -d $(GOFILES)); \
	if [ -n "$$diff" ]; then \
		echo "Please run 'make fmt' and commit the result:"; \
		echo "$${diff}"; \
		exit 1; \
	fi;

$(CMD):
	go build -o bin/$@/falcon-$@ ./modules/$@

dev: $(CMD) $(TARGET)
	@$(foreach var,$(CMD),mkdir -p ./bin/$(var)/bin;)
	@$(foreach var,$(CMD),mkdir -p ./bin/$(var)/config;)
	@$(foreach var,$(CMD),mkdir -p ./bin/$(var)/logs;)
	@$(foreach var,$(CMD),/usr/bin/cp ./config/$(var).json ./bin/$(var)/config/cfg.json;)
	@$(foreach var,$(CMD),/usr/bin/cp ./bin/$(var)/falcon-$(var) ./bin/$(var)/bin;)
	@/usr/bin/cp -r ./modules/agent/public ./bin/agent/
	@-(cd ./bin && ln -s ./agent/public/ ./public)
	@/usr/bin/cp -r ./modules/agent/plugins ./bin/agent/
	@-(cd ./bin && ln -s ./agent/plugins/ ./plugins)
	@/usr/bin/cp -r ./modules/api/data ./bin/api/
	@mkdir -p bin/graph/data
	@bash ./config/dev_confgen.sh
	@/usr/bin/cp $(TARGET) ./bin/$(TARGET)

.PHONY: $(TARGET)
$(TARGET): $(GOFILES)
	go build -ldflags "-X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=$(VERSION)" -o open-falcon
	@mkdir -p ./bin
	@/usr/bin/cp ./$@ ./bin/$@

checkbin: bin/ config/ open-falcon

pack: checkbin
	@if [ -e out ] ; then rm -rf out; fi
	@mkdir out
	@$(foreach var,$(CMD),mkdir -p ./out/$(var)/bin;)
	@$(foreach var,$(CMD),mkdir -p ./out/$(var)/config;)
	@$(foreach var,$(CMD),mkdir -p ./out/$(var)/logs;)
	@$(foreach var,$(CMD),cp ./config/$(var).json ./out/$(var)/config/cfg.json;)
	@$(foreach var,$(CMD),cp ./bin/$(var)/falcon-$(var) ./out/$(var)/bin;)
	@cp -r ./modules/agent/public ./out/agent/
	@(cd ./out && ln -s ./agent/public/ ./public)
	@(cd ./out && mkdir -p ./agent/plugin && ln -s ./agent/plugin/ ./plugin)
	@cp -r ./modules/api/data ./out/api/
	@mkdir out/graph/data
	@bash ./config/confgen.sh
	@cp $(TARGET) ./out/$(TARGET)
	tar -C out -zcf open-falcon-v$(VERSION).tar.gz .
	@rm -rf out

clean:
	@rm -rf ./bin
	@rm -rf ./out
	@rm -rf ./$(TARGET)
	@rm -rf open-falcon-v$(VERSION).tar.gz

.PHONY: clean all agent aggregator graph hbs judge nodata transfer gateway api alarm
